<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="vtiger.tests.LeadsTest" tests="1" time="0.000" ignored="4" failures="0" timestamp="09 May 2019 17:09:36 GMT" skipped="0" hostname="DESKTOP-1G7VPMV" errors="1">
  <testcase name="CreateLeadTC005" time="0.000" classname="vtiger.tests.LeadsTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at vtiger.Pages.LoginPage.login(LoginPage.java:32)
	at vtiger.tests.LeadsTest.CreateLeadTC005(LeadsTest.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </error>
  </testcase> <!-- CreateLeadTC005 -->
  <testcase name="ConvertCreatedLead" classname="vtiger.tests.LeadsTest">
    <skipped/>
  </testcase> <!-- ConvertCreatedLead -->
  <testcase name="verifyLoginInValid_TC03" classname="vtiger.tests.LoginTest">
    <skipped/>
  </testcase> <!-- verifyLoginInValid_TC03 -->
  <testcase name="verifyLoginlogoTC002" classname="vtiger.tests.LoginTest">
    <skipped/>
  </testcase> <!-- verifyLoginlogoTC002 -->
  <testcase name="verifyLoginTitleTC001" classname="vtiger.tests.LoginTest">
    <skipped/>
  </testcase> <!-- verifyLoginTitleTC001 -->
</testsuite> <!-- vtiger.tests.LeadsTest -->
